### PR TITLE
Added more accessors to struct AvCodecParameters.

### PR DESCRIPTION
**Pull request by pushpagarwal**
These accessor would help to set stream codecpar values from javascript. It made possible to mux encoded packets from webcodecs encoder. 
So libav.js could be used for muxing mp4 with AAC1 audio (encoded using livav.js) and H.264 Video ( encoded using webcodecs).

### CODE REVIEW

**Comment by pushpagarwal** [comment]
@Yahweasel Could you please review this PR?

**Comment by Yahweasel** [comment]
> @Yahweasel Could you please review this PR?

I did, the same day you made it. There is a pending review in the PR.

**Comment by pushpagarwal** [comment]
@Yahweasel I don't see any comments on the PR. Please let me know comments pending for me so that I can address those. 
Attaching screenshot of what I see on the PR.
image

**Comment by Yahweasel** [comment]
Oy vey, GitHub gonna GitHub I guess.
image

**Pull request merged**
