### PR TITLE
Remove CommonJS specific code & Fix other packaging issues

### PR DESCRIPTION
**Pull request by longnguyen2004**
The easiest way to solve the problem is to remove the root cause completely :)
Solves #66

After this, Node.js users will need to switch from `require()` to `await import()`, everything else is unchanged. In my opinion, this is a small price to pay instead of trying to do dual CJS + ESM.

I don't have the Emscripten toolchain setup yet. Since my changes didn't touch the WebAssembly parts, is there a way to test it on a published package?

### CODE REVIEW

**Comment by Yahweasel** [comment]
You cannot change the name exported in the types. The types file in libav.js is in extensive use.

**Comment by longnguyen2004** [comment]
I reverted the commit, you can check again

**Comment by longnguyen2004** [comment]
Hello, is this PR good to go?

**Comment by Yahweasel** [comment]
This is a major, non-backwards-compatible change which I am testing and considering. I will not merge it without quite some consideration time.

**Comment by longnguyen2004** [comment]
Close, I found a better way https://github.com/Yahweasel/libav.js/issues/66#issuecomment-2437468926

**Pull request closed without merging**
